//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheJooleProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consumer
    {
        public int ConsumerID { get; set; }
        public string ConsumerName { get; set; }
        public string Email { get; set; }
        public byte[] ConsumerImage { get; set; }
        public string Password { get; set; }
    }
}
