//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TheJooleProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class TechSpecFilter
    {
        public int PropertyID { get; set; }
        public int SubCategoryID { get; set; }
        public int Min_Value { get; set; }
        public int Max_Value { get; set; }
    
        public virtual Property Property { get; set; }
        public virtual SubCategory SubCategory { get; set; }
    }
}
