//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Joole.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropertyValue
    {
        public int PropertyID { get; set; }
        public int ProductID { get; set; }
        public Nullable<double> Value { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Property Property { get; set; }
    }
}
